### ISSUE TITLE
Social share: share to facebook story on iOS background image

### ISSUE THREAD

**Issue by freakness** [appinioGmbH/flutter_packages#127]
When I share to facebook story using `AppinioSocialShare().shareToFacebookStory` the background image contains a weird image regardless of using the `backgroundImage` argument or not.

Screenshot of result in facebook app.

![IMG_6647AB090C78-1](https://github.com/appinioGmbH/flutter_packages/assets/11801732/61345878-c5a5-4a46-bc7b-55a518beb3fa)

example code used:

```
  final AppinioSocialShare _appinioSocialShare = AppinioSocialShare();
...
await _appinioSocialShare.shareToFacebookStory('<AppID>')
```

This only happens on iOS, on android the behaviour is as expected. The correct backgroundImage is added.

**Comment by liubou-s-digitalmara** [comment]
Hi @freakness!

I opened a MR to fix this, but the release branch was merged without my MR, so it got closed. You can check the code though: https://github.com/appinioGmbH/flutter_packages/pull/116

You can also use my branch to check if this fix solves your problem:
```
appinio_social_share:
    git:
      url: https://github.com/liubou-s-digitalmara/flutter_packages.git
      ref: bugfix/facebook-stories-background
      path: packages/appinio_social_share
```

Currently there is no branch for new social share version, so I cannot open a new MR.
@khanmujeeb687 fyi
