### ISSUE TITLE
Error TMS-90809 IOS

### ISSUE THREAD

**Issue by NaosFr** [appinioGmbH/flutter_packages#27]
Hello, when I send the application to appstoreconnect I get this error:

```
TMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).
```

I checked it comes from your package 

Any idea thx 😇

**Comment by bilalhammoud** [comment]
Hey @NicolasCELLA,

What package are you using?

**Comment by NicolasCELLA** [comment]
```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2 ## config++ ##

  # Firebase
  firebase_core: ^1.21.1

  # Notifications
  firebase_messaging: ^12.0.3 ## config++ ## downgrade ?????????????

  # Permissions
  permission_handler: ^10.1.0 ## config++ ##

  # Analytics
  firebase_analytics: ^9.3.3
  firebase_crashlytics: ^2.8.9 ## config++ ##
  amplitude_flutter: ^3.10.0

  # Widgets
  overlay_support: ^2.0.1

  # States & Storage
  get: ^4.6.5
  provider: ^6.0.3
  get_storage: ^2.0.3
  flutter_secure_storage: ^6.0.0

  # Internet
  dio: ^4.0.6
  dio_smart_retry: ^1.3.2
  socket_io_client: ^2.0.0
  connectivity_plus: ^2.3.6+1

  # Image & Svg & Flare & Rive
  rive: ^0.9.1
  octo_image: ^1.0.2
  image_picker: ^0.8.5+3
  image_cropper: ^3.0.0 ## config++ ##
  flutter_cache_manager: ^3.3.0
  cached_network_image: ^3.2.1
  flutter_image_compress: ^1.1.2
  flutter_svg: ^1.1.4

  # Phone & Contacts
  phone_number: ^1.0.0
  flutter_sms: ^2.3.3 ## config++ ##
  contacts_service: ^0.6.3 ## config++ ##

  # Streaming
  spotify: ^0.8.0

  # Audio
  just_audio: ^0.9.29

  # Utils
  uuid: ^3.0.6
  intl: ^0.17.0
  social_share: ^2.2.1
 appinio_social_share: ^0.1.1
  scroll_snap_list: ^0.9.1
  flutter_inappwebview: ^5.4.4+3
  diacritic: ^0.1.3
  http_parser: ^4.0.1
  path_provider: ^2.0.11
  easy_debounce: ^2.0.2+1
  in_app_review: ^2.0.4
  auto_size_text: ^3.0.0
  auto_size_text_field: ^2.1.0
  url_launcher: ^6.1.5 ## config++ ##
  app_settings: ^4.1.8
  share_plus: ^4.0.10+1
  flare_flutter:
    git:
      url: https://github.com/mdpe-ir/Flare-Flutter
      path: flare_flutter
      ref: stable
  package_info_plus: ^1.4.2
  vector_math: ^2.1.2
  flutter_keyboard_visibility: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ```
  
  
  But when i remove appinio_social_share i doesn't have this problem  🤔
