### ISSUE TITLE
[ BUG ] : * What went wrong: Execution failed for task ':cached_video_player:verifyReleaseResources'. > A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action    > Android resource linking failed      ERROR:C:\salin_salita\salinsalita\build\cached_video_player\intermediates\merged_res\release\values\values.xml:141: AAPT: error: resource android:attr/lStar not found.

### ISSUE THREAD

**Issue by voltohmmeter** [appinioGmbH/flutter_packages#285]
While running flutter build apk I continuously get that error.

**Comment by Abdullah104** [comment]
Me too. I had to revert to building an appbundle instead of an apk to get around it, As I don't face this issue when running `flutter build appbundle` unlike `flutter build apk`

**Comment by chauhanpriyanshu001** [comment]
same error

**Comment by JahnChoi** [comment]
Consider using the following snippet to override the `cached_video_player` dependency with the Gradle bump fix from a forked repo.

In your `pubspec.yaml` add the following:
```
dependency_overrides:
  cached_video_player:
    git:
      url: https://github.com/vikram25897/flutter_cached_video_player
      ref: feature/gradle_version_bump
```
